name: Validate and Lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Lint
        run: |
          pip install flake8
          flake8 --max-line-length=120 || true
      - name: Run syntax check
        run: python -m py_compile ai_audit_agent.py stig_runner.py || true
